# -*- coding: utf-8 -*-
"""Train_En_Vi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OoWBJDXAGo_yzEdYGl2USJZ2MjcjaTwd
"""

!pip install -U psycopg2-binary sqlalchemy pandas datasets peft torchao transformers sentencepiece sacremoses accelerate evaluate sacrebleu

import pandas as pd
from sqlalchemy import create_engine
from datasets import Dataset

# 1. Chuỗi kết nối
DB_URL = "postgresql://postgres.jkaazcjahfqozwizhpvk:Khaiphadulieu@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres"

print("Đang kết nối tới Supabase...")
engine = create_engine(DB_URL)

# 2. Truy vấn dữ liệu theo Chunk
chunk_size = 50000
query = "SELECT english_text, vietnamese_text FROM raw_data WHERE english_text IS NOT NULL AND vietnamese_text IS NOT NULL;"

print("Bắt đầu tải dữ liệu từ kho...")
try:
    chunks = pd.read_sql_query(query, engine, chunksize=chunk_size)

    df_list = []
    for i, chunk in enumerate(chunks):
        chunk = chunk.dropna()
        df_list.append(chunk)
        if (i+1) % 5 == 0:
            print(f"✅ Đã tải xong phần {i+1}")

    full_df = pd.concat(df_list, ignore_index=True)
    print(f"\n TỔNG SỐ CÂU GỐC: {len(full_df)}")

    target_size = 600000
    if len(full_df) > target_size:
        print(f"Đang lấy ngẫu nhiên {target_size} dòng để tối ưu tốc độ train...")
        full_df = full_df.sample(n=target_size, random_state=42).reset_index(drop=True)

    print(f"✅ SỐ LƯỢNG DÙNG ĐỂ TRAIN: {len(full_df)}")

    # 3. ÉP CÂN DỮ LIỆU BẰNG HUGGING FACE DATASET
    print("Đang ép kiểu dữ liệu sang Hugging Face format...")
    hf_dataset = Dataset.from_pandas(full_df)

    print("\n Xem thử 3 mẫu dữ liệu đầu tiên:")
    print(hf_dataset[:3])

except Exception as e:
    print(f"\n❌ Lỗi: {e}")

from transformers import AutoTokenizer

# 1. Chọn model chuẩn cho dịch Anh-Việt làm Tokenizer
checkpoint = "Helsinki-NLP/opus-mt-en-vi"
print(f"Đang tải Tokenizer từ: {checkpoint}...")
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

# 2. Chia tập dữ liệu (95% Train - 5% Validation)
print("Đang chia tập Train và Validation...")
split_datasets = hf_dataset.train_test_split(test_size=0.05, seed=42)

# 3. Hàm tiền xử lý (Tokenization)
max_length = 64

def preprocess_function(examples):
    inputs = examples["english_text"]
    targets = examples["vietnamese_text"]

    model_inputs = tokenizer(inputs, max_length=max_length, truncation=True)
    labels = tokenizer(text_target=targets, max_length=max_length, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

# 4. Áp dụng hàm trên cho toàn bộ dữ liệu
print("Bắt đầu Tokenize (Biến chữ thành số) - Quá trình này sẽ mất vài phút để xử lý 1.8 triệu câu...")
tokenized_datasets = split_datasets.map(
    preprocess_function,
    batched=True,
    num_proc=4,
    remove_columns=split_datasets["train"].column_names,
    desc="Đang Tokenize dữ liệu"
)

print("\n Tokenize thành công! Cấu trúc dữ liệu mới:")
print(tokenized_datasets)

# 5. LƯU VÀO Ổ CỨNG COLAB
print("\nĐang lưu dữ liệu đã tokenize vào ổ đĩa Colab...")
tokenized_datasets.save_to_disk("tokenized_en_vi_data")
print("✅ Đã lưu xong! Lần sau mở Colab chỉ cần load lại thư mục 'tokenized_en_vi_data' là xong, không phải kết nối Supabase hay Tokenize lại nữa.")

import numpy as np
import evaluate
from transformers import AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainingArguments, Seq2SeqTrainer
from peft import LoraConfig, get_peft_model, TaskType

# 1. Tải mô hình lõi (Base Model) vào GPU
checkpoint = "Helsinki-NLP/opus-mt-en-vi"
print("Đang tải Base Model...")
model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)

# A. Đóng băng Encoder
for param in model.get_encoder().parameters():
    param.requires_grad = False

# B. Áp dụng LoRA
peft_config = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    inference_mode=False,
    r=8,
    lora_alpha=32,
    lora_dropout=0.1,
    target_modules=["q_proj", "v_proj"]
)

model = get_peft_model(model, peft_config)
model.print_trainable_parameters()


# 2. Data Collator: Tự động đệm (padding) các câu cho bằng nhau trong mỗi lượt train (Tiết kiệm RAM)
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

# 3. Cài đặt công cụ tính điểm BLEU
metric = evaluate.load("sacrebleu")

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]

    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    decoded_labels = [[label] for label in decoded_labels]

    result = metric.compute(predictions=decoded_preds, references=decoded_labels)
    return {"bleu": result["score"]}

# 4. TỐI ƯU HÓA SIÊU THAM SỐ CHO COLAB
print("Đang thiết lập thông số huấn luyện tối ưu...")
training_args = Seq2SeqTrainingArguments(
    output_dir="./en_vi_translation_model",
    eval_strategy="epoch",
    learning_rate=2e-4,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    save_total_limit=2,
    num_train_epochs=3,
    predict_with_generate=True,
    fp16=True,
    gradient_accumulation_steps=2,
    dataloader_num_workers=2,
    logging_steps=200,
)

# 5. Ép cân tập Validation
print("Đang rút gọn tập Validation...")
small_eval_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(2000))

# 6. Lắp ráp cỗ máy Trainer
print("Đang lắp ráp Trainer...")
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=small_eval_dataset,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

print("\n LẮP RÁP THÀNH CÔNG! HỆ THỐNG ĐÃ SẴN SÀNG HUẤN LUYỆN.")

# 7. BẤM NÚT KHỞI ĐỘNG (TRAINING)
print("Bắt đầu quá trình huấn luyện (Fine-tuning)... GPU")
trainer.train()

# 8. LƯU MÔ HÌNH SAU KHI TRAIN XONG (Để chuẩn bị đẩy lên Hugging Face)
print("Đang lưu mô hình hoàn chỉnh...")
trainer.save_model("./en_vi_translation_model_final")
print("ĐÃ HOÀN THÀNH TOÀN BỘ QUÁ TRÌNH HUẤN LUYỆN!")

import torch
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from peft import PeftModel

# 1. Định nghĩa đường dẫn
base_model_name = "Helsinki-NLP/opus-mt-en-vi"
adapter_path = "./en_vi_translation_model_final"

# 2. Tải Base Model và Tokenizer
print("Đang tải lại Base Model gốc...")
en_vi_tokenizer = AutoTokenizer.from_pretrained(base_model_name)
base_model = AutoModelForSeq2SeqLM.from_pretrained(base_model_name)

# 3. Gộp LoRA Adapter vào Base Model
print("Đang gộp bản vá LoRA vào Base Model (Merge Weights)...")
model_to_merge = PeftModel.from_pretrained(base_model, adapter_path)
merged_en_vi_model = model_to_merge.merge_and_unload() # Lệnh quan trọng nhất để xuất xưởng

# 4. Lưu lại Model ĐÃ GỢP để chuẩn bị cho TFLite
merged_model_path = "./merged_en_vi_model"
merged_en_vi_model.save_pretrained(merged_model_path)
en_vi_tokenizer.save_pretrained(merged_model_path)
print(f"✅ Đã lưu model HOÀN CHỈNH tại thư mục: {merged_model_path}")

# 5. TẠO HÀM DỊCH ANH -> VIỆT (TÁI SỬ DỤNG)
def dich_anh_viet(cau_tieng_anh):
    inputs = en_vi_tokenizer(cau_tieng_anh, return_tensors="pt")
    outputs = merged_en_vi_model.generate(**inputs, max_length=64)
    return en_vi_tokenizer.decode(outputs[0], skip_special_tokens=True)

# Test thử hàm
print("\n BẮT ĐẦU DỊCH THỬ:")
cau_test = "Knowledge Graph combined with Edge AI is a powerful weapon for our project."
ket_qua = dich_anh_viet(cau_test)

print(f"🇺🇸 Tiếng Anh: {cau_test}")
print(f"🇻🇳 Tiếng Việt: {ket_qua}")

print(dich_anh_viet("I feel tired"))
print(dich_anh_viet("I love you"))

from huggingface_hub import notebook_login

# Khi chạy sẽ hiện ô nhập Token.
# Bạn lấy Token (quyền WRITE) tại: https://huggingface.co/settings/tokens
notebook_login()

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

# 1.
repo_name_en_vi = "Dich-Thuat-AI-Nhom-05/en-vi-translator"

print("Đang tải mô hình En-Vi đã gộp sẵn từ Colab...")
# Trỏ vào thư mục đã lưu model hoàn chỉnh
merged_dir_en_vi = "./merged_en_vi_model"

# Tải Model và Tokenizer từ thư mục cục bộ
model_en_vi = AutoModelForSeq2SeqLM.from_pretrained(merged_dir_en_vi)
tokenizer_en_vi = AutoTokenizer.from_pretrained(merged_dir_en_vi)

# 3. Đẩy lên Hugging Face
print(f"Đang đẩy mô hình En-Vi lên: {repo_name_en_vi} (có thể mất vài phút)...")
model_en_vi.push_to_hub(repo_name_en_vi)
tokenizer_en_vi.push_to_hub(repo_name_en_vi)

print("Hoàn thành! Đã đẩy thành công mô hình Anh-Việt lên kho của Nhóm 05.")