# -*- coding: utf-8 -*-
"""KPDL_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dilH1hyzGJtvQBUF6HHyb_fl-YWRt_-n
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
try:

    df = pd.read_csv('raw_data.csv')

    # 2. Tính độ dài câu dựa trên số từ (word count)
    # Dùng hàm split() để tách từ theo khoảng trắng
    df['en_word_count'] = df['english_text'].apply(lambda x: len(str(x).split()))
    df['vi_word_count'] = df['vietnamese_text'].apply(lambda x: len(str(x).split()))

    # 3. Cấu hình khung hình
    plt.figure(figsize=(16, 6))
    sns.set_theme(style="whitegrid") # Giao diện biểu đồ sạch sẽ

    # Biểu đồ Histogram cho tiếng Anh
    plt.subplot(1, 2, 1)
    sns.histplot(df['en_word_count'], bins=50, kde=True, color='#2c7bb6')
    plt.title('Histogram Độ dài câu Tiếng Anh', fontsize=14, fontweight='bold')
    plt.xlabel('Số từ trong một câu', fontsize=12)
    plt.ylabel('Số lượng câu', fontsize=12)

    # Biểu đồ Histogram cho tiếng Việt
    plt.subplot(1, 2, 2)
    sns.histplot(df['vi_word_count'], bins=50, kde=True, color='#d7191c')
    plt.title('Histogram Độ dài câu Tiếng Việt', fontsize=14, fontweight='bold')
    plt.xlabel('Số từ trong một câu', fontsize=12)
    plt.ylabel('Số lượng câu', fontsize=12)

    plt.tight_layout()
    plt.show()

except FileNotFoundError:
    print("Lỗi: Không tìm thấy file 'raw_data.csv'. Vui lòng kiểm tra lại đường dẫn.")
except Exception as e:
    print(f"Có lỗi xảy ra: {e}")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Đọc dữ liệu
try:
    df = pd.read_csv('raw_data.csv')

    # 2. Tính độ dài câu (số từ)
    df['en_word_count'] = df['english_text'].apply(lambda x: len(str(x).split()))
    df['vi_word_count'] = df['vietnamese_text'].apply(lambda x: len(str(x).split()))

    # 3. Chuyển đổi dữ liệu sang dạng "long-form" để phù hợp với Seaborn
    # Điều này giúp vẽ cả 2 ngôn ngữ trên cùng 1 trục tọa độ để dễ so sánh
    df_long = pd.melt(df[['en_word_count', 'vi_word_count']],
                      var_name='Ngôn ngữ',
                      value_name='Độ dài câu (số từ)')

    # Đổi tên hiển thị cho đẹp
    df_long['Ngôn ngữ'] = df_long['Ngôn ngữ'].map({
        'en_word_count': 'Tiếng Anh',
        'vi_word_count': 'Tiếng Việt'
    })

    # 4. Vẽ Boxplot
    plt.figure(figsize=(10, 7))
    sns.set_theme(style="whitegrid")

    # Vẽ biểu đồ với màu sắc phân biệt
    sns.boxplot(x='Ngôn ngữ', y='Độ dài câu (số từ)', data=df_long, palette=['#3498db', '#e74c3c'])

    # 5. Tinh chỉnh tiêu đề và nhãn
    plt.title('So sánh phân phối độ dài câu bằng Boxplot', fontsize=14, fontweight='bold')
    plt.xlabel('Ngôn ngữ', fontsize=12)
    plt.ylabel('Số lượng từ', fontsize=12)

    # Hiển thị biểu đồ
    plt.tight_layout()
    plt.show()

except FileNotFoundError:
    print("Lỗi: Không tìm thấy file 'raw_data.csv'.")
except Exception as e:
    print(f"Có lỗi xảy ra: {e}")

import pandas as pd

# Giả định dữ liệu đã được load vào df
# df = pd.read_csv('raw_data.csv')

# 1. Thống kê chỉ số độ dài (Mean, Max, Min)
def get_length_stats(df):
    stats = {
        'Metric': ['Mean length', 'Max length', 'Min length'],
        'English': [
            df['english_text'].str.split().str.len().mean(),
            df['english_text'].str.split().str.len().max(),
            df['english_text'].str.split().str.len().min()
        ],
        'Vietnamese': [
            df['vietnamese_text'].str.split().str.len().mean(),
            df['vietnamese_text'].str.split().str.len().max(),
            df['vietnamese_text'].str.split().str.len().min()
        ]
    }
    return pd.DataFrame(stats)

# 2. Thống kê các loại dữ liệu lỗi
def get_error_counts(df):
    # Dữ liệu thiếu
    missing = df[['english_text', 'vietnamese_text']].isnull().any(axis=1).sum()

    # Dữ liệu trùng lặp
    duplicates = df.duplicated(subset=['english_text', 'vietnamese_text']).sum()

    # Outliers dựa trên tỷ lệ độ dài (ví dụ: chênh lệch > 3 lần)
    en_len = df['english_text'].str.split().str.len()
    vi_len = df['vietnamese_text'].str.split().str.len()
    # Tránh chia cho 0 bằng cách cộng epsilon hoặc chỉ xét câu có độ dài > 0
    ratio = en_len / vi_len.replace(0, 1)
    outliers = ((ratio > 3) | (ratio < 1/3)).sum()

    error_stats = {
        'Loại dữ liệu': ['Missing values', 'Duplicate records', 'Outlier sentences'],
        'Số lượng': [missing, duplicates, outliers]
    }
    return pd.DataFrame(error_stats)

# Thực thi và hiển thị
df_length_stats = get_length_stats(df)
df_error_counts = get_error_counts(df)

print("--- Bảng chỉ số độ dài ---")
print(df_length_stats.to_markdown(index=False))
print("\n--- Bảng thống kê dữ liệu lỗi ---")
print(df_error_counts.to_markdown(index=False))

"""# Import Thư viện & Định nghĩa Hàm Xử lý"""

# CÀI ĐẶT THƯ VIỆN CẦN THIẾT
!pip install langdetect sqlalchemy psycopg2-binary pandas spacy sentence-transformers -q
!python -m spacy download en_core_web_sm -q

# IMPORT THƯ VIỆN
import pandas as pd
import re
from langdetect import detect, LangDetectException
from sqlalchemy import create_engine
import spacy
from sentence_transformers import SentenceTransformer

# ĐỊNH NGHĨA CÁC HÀM XỬ LÝ TEXT CƠ BẢN
def clean_text(text):
    text = str(text)
    text = re.sub(r'<.*?>', '', text)           # Xóa HTML
    text = re.sub(r'http\S+|www\S+', '', text)  # Xóa Link
    text = re.sub(r'&\w+;', '', text)           # Xóa ký tự escape
    text = re.sub(r'\s+', ' ', text).strip()    # Xóa khoảng trắng thừa
    return text

def word_count(text):
    return len(str(text).split())

# "KHIÊN REGEX" - CHẶN KÝ TỰ NGOẠI LAI (Nga, Trung, Hàn, Emoji...)
STRICT_PATTERN = re.compile(
    r'^[a-zA-Z0-9\s.,?!:;\'"()\[\]{}&%$#@*_\-+=<>~/\\|'
    r'àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ'
    r'ÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ]+$'
)

def is_strictly_clean(text):
    if pd.isna(text) or text == "":
        return False
    return bool(STRICT_PATTERN.match(str(text)))

# "KHIÊN NGỮ NGHĨA" - KIỂM TRA BẰNG LANGDETECT
def is_actually_english(text):
    try:
        return detect(str(text)) == 'en'
    except LangDetectException:
        return False

"""# Hàm xử lý dữ liệu"""

INPUT_FILE = "/content/raw_data.csv"
df = pd.read_csv(INPUT_FILE, encoding='utf-8')
print(f"Tổng dòng ban đầu: {len(df):,}")

# XÓA NULL VÀ LÀM SẠCH CƠ BẢN
df = df.dropna(subset=['english_text', 'vietnamese_text'])
df['english_text'] = df['english_text'].apply(clean_text)
df['vietnamese_text'] = df['vietnamese_text'].apply(clean_text)
df = df[(df['english_text'] != '') & (df['vietnamese_text'] != '')]

# DIỆT LỖI #VALUE CỦA EXCEL
df = df[~df['english_text'].str.contains('#value|#VALUE!', na=False, case=False)]
df = df[~df['vietnamese_text'].str.contains('#value|#VALUE!', na=False, case=False)]

# XÓA TRÙNG LẶP
df = df.drop_duplicates(subset=['english_text', 'vietnamese_text'])

# LỌC BẰNG KHIÊN REGEX (Loại bỏ tiếng Nga, Trung, v.v.)
print("Đang quét ký tự lạ bằng Regex...")
df = df[
    df['english_text'].apply(is_strictly_clean) &
    df['vietnamese_text'].apply(is_strictly_clean)
]

# LỌC ĐỘ DÀI VÀ LỆCH PHA (Vi/En)
df['en_word_count'] = df['english_text'].apply(word_count)
df['vi_word_count'] = df['vietnamese_text'].apply(word_count)
df['length_ratio'] = df['vi_word_count'] / df['en_word_count']
df = df[
    (df['en_word_count'].between(5, 80)) &
    (df['vi_word_count'].between(5, 80)) &
    (df['length_ratio'].between(0.33, 3.0))
]
df = df.drop(columns=['en_word_count', 'vi_word_count', 'length_ratio'])

print(f"Sau khi dọn dẹp cơ bản còn {len(df):,} dòng.")

"""# Oversampling, Quét Ngữ Nghĩa & Chốt 600k dòng


"""

TARGET_ROWS = 600_000
OVERSAMPLE_SIZE = 650_000

# CẮT MẪU (OVERSAMPLING) ĐỂ TĂNG TỐC ĐỘ LANGDETECT
if len(df) > OVERSAMPLE_SIZE:
    df = df.sample(n=OVERSAMPLE_SIZE, random_state=42)
    print(f"Đã cắt mẫu xuống {OVERSAMPLE_SIZE:,} dòng để tăng tốc quét ngôn ngữ.")

print("Đang kiểm tra ngữ nghĩa bằng LangDetect")
df = df[df['english_text'].apply(is_actually_english)]

# 600k dòng
if len(df) > TARGET_ROWS:
    df = df.sample(n=TARGET_ROWS, random_state=42)

df = df.reset_index(drop=True)

# CHUẨN BỊ CỘT SOURCE
if 'source' not in df.columns:
    df['source'] = 'phoMT'
else:
    df['source'] = df['source'].fillna('phoMT')

df = df[['english_text', 'vietnamese_text', 'source']]
print(f" Đã có {len(df):,} dòng dữ liệu hoàn hảo.")

# LƯU VÀ TẢI FILE CSV
OUTPUT_FILE = "/content/data_600k_clean.csv"
df.to_csv(OUTPUT_FILE, index=False, encoding='utf-8-sig')

from google.colab import files
files.download(OUTPUT_FILE)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. ĐỌC DỮ LIỆU
# Giả sử file raw_data.csv và data_600k_clean.csv đang ở cùng thư mục
df_raw = pd.read_csv("raw_data.csv")
df_clean = pd.read_csv("data_600k_clean.csv")

# Cài đặt cấu hình chung cho biểu đồ
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (15, 12)

# Hàm tính số lượng từ
def count_words(text):
    return len(str(text).split())

# --- BIỂU ĐỒ 1: HISTOGRAM ĐỘ DÀI CÂU SAU CLEANING ---
plt.subplot(2, 2, 1)
sns.histplot(df_clean['english_text'].apply(count_words), color="skyblue", label='English', kde=True, bins=30)
sns.histplot(df_clean['vietnamese_text'].apply(count_words), color="salmon", label='Vietnamese', kde=True, bins=30)
plt.title('1. Histogram: Phân phối độ dài câu (Sau Cleaning)')
plt.xlabel('Số lượng từ')
plt.ylabel('Tần suất')
plt.legend()

# --- BIỂU ĐỒ 2: SO SÁNH TRƯỚC VS SAU CLEANING ---
plt.subplot(2, 2, 2)
stats = pd.DataFrame({
    'Trạng thái': ['Trước Cleaning', 'Sau Cleaning'],
    'Số dòng': [len(df_raw), len(df_clean)]
})
ax = sns.barplot(x='Trạng thái', y='Số dòng', data=stats, palette='viridis')
# Hiển thị con số cụ thể trên đầu cột
for p in ax.patches:
    ax.annotate(f'{int(p.get_height()):,}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', xytext=(0, 10), textcoords='offset points', weight='bold')
plt.title('2. So sánh tổng số lượng dữ liệu (Before vs After)')
plt.ylabel('Số lượng dòng')

# --- BIỂU ĐỒ 3: BOXPLOT ĐỘ DÀI CÂU SAU CLEANING ---
plt.subplot(2, 1, 2)
# Chuẩn bị dữ liệu cho boxplot
en_lens = df_clean['english_text'].apply(count_words)
vi_lens = df_clean['vietnamese_text'].apply(count_words)
df_boxplot = pd.DataFrame({
    'Số lượng từ': pd.concat([en_lens, vi_lens]),
    'Ngôn ngữ': ['English'] * len(df_clean) + ['Vietnamese'] * len(df_clean)
})

sns.boxplot(x='Ngôn ngữ', y='Số lượng từ', data=df_boxplot, palette='Set2')
plt.title('3. Boxplot: Kiểm tra Outliers độ dài câu (Sau Cleaning)')
plt.ylabel('Số từ trong một câu')

plt.tight_layout()
plt.show()

"""# Tạo 100 dòng dữ liệu giả cho bảng translation_history"""

from supabase import create_client

SUPABASE_URL = "https://jkaazcjahfqozwizhpvk.supabase.co"

SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprYWF6Y2phaGZxb3p3aXpocHZrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzQ5Njg5NSwiZXhwIjoyMDkzMDcyODk1fQ.mLjVZFPMhkmFwYgOmsq6WCVG8pyQ0IGDT53-M-J5c8Y"

supabase = create_client(
    SUPABASE_URL,
    SUPABASE_KEY
)

test = supabase.table(
    "knowledge_graph_entities"
).insert({

    "entity_name": "Python",

    "normalized_name": "python",

    "entity_type": "PROGRAMMING_LANGUAGE",

    "language": "en",

    "frequency": 1,

    "embedding": [0.0] * 384

}).execute()

print(test)

import pandas as pd
import random
import uuid
from datetime import datetime, timedelta
from sqlalchemy import create_engine

# KẾT NỐI SUPABASE
CONN_STRING = "postgresql://postgres.jkaazcjahfqozwizhpvk:Khaiphadulieu@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres"
engine = create_engine(CONN_STRING)

# CHUẨN BỊ 30 CẶP CÂU ĐA DẠNG
eng_sentences = [
    'Hello', 'Good morning', 'How are you?', 'Thank you very much', 'I am sorry',
    'What is your name?', 'See you later', 'Have a nice day', 'Where is the hospital?',
    'I love programming', 'Artificial Intelligence is the future', 'Can you help me?',
    'This food is delicious', 'How much does this cost?', 'I am learning Vietnamese',
    'What time is it?', 'I need a doctor', 'Where is the restroom?', 'The weather is beautiful today',
    'I like to read books', 'Happy birthday!', 'Congratulations!', 'I do not understand',
    'Please speak slowly', 'Could you repeat that?', 'Where are you from?', 'I am from Vietnam',
    'What do you do for a living?', 'Call the police!', 'I lost my wallet'
]

vie_sentences = [
    'Xin chào', 'Chào buổi sáng', 'Bạn khỏe không?', 'Cảm ơn rất nhiều', 'Tôi xin lỗi',
    'Bạn tên là gì?', 'Hẹn gặp lại', 'Chúc một ngày tốt lành', 'Bệnh viện ở đâu?',
    'Tôi yêu lập trình', 'Trí tuệ nhân tạo là tương lai', 'Bạn có thể giúp tôi không?',
    'Món ăn này rất ngon', 'Cái này giá bao nhiêu?', 'Tôi đang học tiếng Việt',
    'Bây giờ là mấy giờ?', 'Tôi cần bác sĩ', 'Nhà vệ sinh ở đâu?', 'Thời tiết hôm nay rất đẹp',
    'Tôi thích đọc sách', 'Chúc mừng sinh nhật!', 'Xin chúc mừng!', 'Tôi không hiểu',
    'Làm ơn nói chậm lại', 'Bạn có thể nhắc lại không?', 'Bạn từ đâu đến?', 'Tôi đến từ Việt Nam',
    'Bạn làm nghề gì?', 'Gọi cảnh sát đi!', 'Tôi bị mất ví'
]

# Tạo sẵn 10 UUID giả lập 10 chiếc điện thoại
mock_devices = [str(uuid.uuid4()) for _ in range(10)]

# 3. TẠO 100 DÒNG DỮ LIỆU
mock_data = []
now = datetime.now()

print("Đang tạo 100 dòng Mock Data với 30 câu ngẫu nhiên...")
for _ in range(100):
    idx = random.randint(0, 29) # Chọn ngẫu nhiên 1 trong 30 câu

    # Random ngày giờ lùi về quá khứ trong vòng 30 ngày
    random_days_ago = random.uniform(0, 30)
    created_at = now - timedelta(days=random_days_ago)

    mock_data.append({
        'device_id': random.choice(mock_devices),
        'input_text': eng_sentences[idx],
        'output_text': vie_sentences[idx],
        'model_version': random.choice(['v1.0', 'v1.1', 'v1.2']),
        'is_favorite': random.random() < 0.25,
        'rating': random.randint(1, 5), # Ngẫu nhiên đều đặn từ 1 đến 5 sao
        'created_at': created_at
    })

# Biến thành DataFrame
df_mock = pd.DataFrame(mock_data)

# BƠM LÊN BẢNG TRANSLATION_HISTORY
print("Đang đẩy dữ liệu lên Database...")
try:
    df_mock.to_sql('translation_history', engine, if_exists='append', index=False, method='multi')
    print("Thành công! Đã nạp 100 dòng vào Supabase.")
except Exception as e:
    print(f"Lỗi khi nạp dữ liệu: {e}")

# Thống kê lượt dịch theo ngày (Sắp xếp theo thứ tự thời gian)
df_mock['date'] = df_mock['created_at'].dt.date
daily_stats = df_mock.groupby('date').size().reset_index(name='so_luot_dich')
print("\nTHỐNG KÊ LƯỢT DỊCH THEO NGÀY :")
print(daily_stats.to_string(index=False))

# Thống kê số lượng sao đánh giá (Được dàn đều ngẫu nhiên)
rating_stats = df_mock['rating'].value_counts().reset_index()
rating_stats.columns = ['so_sao', 'so_luong']
rating_stats = rating_stats.sort_values('so_sao', ascending=False)
print("\nTHỐNG KÊ RATING (Để vẽ Pie/Bar Chart):")
print(rating_stats.to_string(index=False))

"""# Knowledge Graph"""

import re
import os
import pandas as pd

from tqdm import tqdm

from unidecode import unidecode

from supabase import create_client

from sentence_transformers import SentenceTransformer

from transformers import pipeline


# =========================================================
# SUPABASE CONFIG
# =========================================================

SUPABASE_URL = "https://jkaazcjahfqozwizhpvk.supabase.co"

SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprYWF6Y2phaGZxb3p3aXpocHZrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzQ5Njg5NSwiZXhwIjoyMDkzMDcyODk1fQ.mLjVZFPMhkmFwYgOmsq6WCVG8pyQ0IGDT53-M-J5c8Y"



# =========================================================
# CONNECT SUPABASE
# =========================================================

supabase = create_client(
    SUPABASE_URL,
    SUPABASE_KEY
)

print("SUPABASE CONNECTED")


# =========================================================
# TEST CONNECTION
# =========================================================

try:

    test = supabase.table(
        "knowledge_graph_entities"
    ).select("*").limit(1).execute()

    print("SUPABASE TEST SUCCESS")

except Exception as e:

    print("SUPABASE CONNECTION ERROR")
    print(e)


# =========================================================
# EMBEDDING MODEL
# =========================================================
#
# 384 dimensions
#
# Better multilingual support
#
# =========================================================

embedding_model = SentenceTransformer(
    "intfloat/multilingual-e5-small"
)

print("EMBEDDING MODEL LOADED")


# =========================================================
# NER MODEL
# =========================================================

ner_pipeline = pipeline(

    "ner",

    model="dslim/bert-base-NER",

    aggregation_strategy="simple"
)

print("NER MODEL LOADED")


# =========================================================
# GLOBAL CACHE
# =========================================================

entity_cache = {}


# =========================================================
# LABEL MAP
# =========================================================

LABEL_MAP = {

    "PER": "PERSON",
    "PERSON": "PERSON",

    "ORG": "ORG",

    "LOC": "LOCATION",
    "GPE": "LOCATION",

    "MISC": "OTHER"
}


# =========================================================
# STOPWORDS
# =========================================================

STOPWORDS = {

    "the",
    "this",
    "that",

    "may",
    "june",
    "july",

    "monday",
    "tuesday",

    "wednesday",
    "thursday",

    "friday",
    "saturday",
    "sunday"
}


# =========================================================
# GAZETTEERS
# =========================================================

KNOWN_LOCATIONS = {

    "hanoi",
    "ha noi",

    "ho chi minh city",
    "hcmc",
    "tphcm",

    "vietnam",

    "france",
    "italy",

    "tokyo",
    "paris",
    "london"
}


PROGRAMMING_LANGUAGES = {

    "python",
    "java",
    "javascript",
    "typescript",

    "c++",
    "c#",

    "go",
    "rust",

    "php",
    "swift",
    "kotlin",

    "ruby"
}


FRAMEWORKS = {

    "react",
    "nextjs",
    "vue",

    "django",
    "flask",
    "fastapi",

    "tensorflow",
    "pytorch",

    "keras",

    "langchain",

    "transformers",

    "spacy"
}


DATABASES = {

    "postgresql",
    "mysql",
    "mongodb",

    "redis",
    "sqlite",

    "supabase",

    "firebase"
}


CLOUDS = {

    "aws",
    "azure",

    "google cloud",
    "gcp",

    "vercel"
}


MODELS = {

    "phobert",
    "bert",

    "xlm-r",

    "llama",

    "gpt-4",
    "gpt-3.5",

    "mistral",

    "gemini",

    "deepseek"
}


TECH_TERMS = {

    "api",
    "rest api",

    "graphql",

    "docker",
    "kubernetes",

    "gpu",
    "cpu",

    "embedding",

    "rag",

    "vector database",

    "machine learning",
    "deep learning"
}


FOOD_WORDS = {

    "oregano",
    "salt",
    "pepper",
    "garlic"
}


LOCATION_HINTS = [

    "city",
    "province",

    "district",
    "country",

    "street",

    "ward"
]


# =========================================================
# NORMALIZE ENTITY
# =========================================================

def normalize_entity(text):

    text = str(text)

    text = text.lower()

    text = unidecode(text)

    text = re.sub(
        r"[^a-z0-9 ]",
        "",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


# =========================================================
# CLEAN TEXT
# =========================================================

def clean_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    text = text.strip()

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text


# =========================================================
# MAP ENTITY LABEL
# =========================================================

def map_entity_label(label):

    label = label.upper()

    return LABEL_MAP.get(
        label,
        "OTHER"
    )


# =========================================================
# FIX ENTITY TYPE
# =========================================================

def fix_entity_type(entity, label):

    lower = normalize_entity(
        entity
    )

    if lower in PROGRAMMING_LANGUAGES:
        return "PROGRAMMING_LANGUAGE"

    if lower in FRAMEWORKS:
        return "FRAMEWORK"

    if lower in DATABASES:
        return "DATABASE"

    if lower in CLOUDS:
        return "CLOUD"

    if lower in MODELS:
        return "MODEL"

    if lower in TECH_TERMS:
        return "TECH"

    if lower in FOOD_WORDS:
        return "FOOD"

    if any(
        hint in lower
        for hint in LOCATION_HINTS
    ):
        return "LOCATION"

    if lower in KNOWN_LOCATIONS:
        return "LOCATION"

    return label


# =========================================================
# GENERATE EMBEDDING
# =========================================================

def generate_embedding(text):

    try:

        embedding = embedding_model.encode(
            f"passage: {text}"
        )

        return embedding.tolist()

    except Exception as e:

        print("EMBEDDING ERROR")
        print(text)
        print(e)

        return [0.0] * 384


# =========================================================
# RULE-BASED IT ENTITY EXTRACTION
# =========================================================

def extract_it_entities(text):

    entities = []

    lowered = text.lower()

    all_terms = (

        PROGRAMMING_LANGUAGES
        | FRAMEWORKS
        | DATABASES
        | CLOUDS
        | MODELS
        | TECH_TERMS
    )

    for term in all_terms:

        pattern = (
            r"\b"
            + re.escape(term.lower())
            + r"\b"
        )

        if re.search(
            pattern,
            lowered
        ):

            entities.append({

                "entity": term,

                "entity_type": fix_entity_type(
                    term,
                    "TECH"
                ),

                "confidence": 1.0
            })

    return entities


# =========================================================
# PROCESS TEXT
# =========================================================

def process_text(text):

    seen = set()

    entities = []

    try:

        ner_results = ner_pipeline(
            text
        )

        for item in ner_results:

            entity = item["word"]

            # ======================================
            # FIX WORDPIECE
            # ======================================

            entity = re.sub(
                r"^##",
                "",
                entity
            )


            entity = entity.strip()

            if not entity:
                continue
            if len(entity) <= 2:
                continue

            if entity.startswith("#"):
                continue

            # ======================================
            # FILTER SHORT ENTITY
            # ======================================

            if len(entity) <= 2:
                continue

            normalized = normalize_entity(
                entity
            )

            # ======================================
            # STOPWORDS
            # ======================================

            if normalized in STOPWORDS:
                continue

            # ======================================
            # DEDUP
            # ======================================

            if normalized in seen:
                continue

            seen.add(normalized)

            # ======================================
            # LABEL
            # ======================================

            label = item["entity_group"]

            confidence = float(
                item["score"]
            )

            if confidence < 0.7:
                continue

            label = map_entity_label(
                label
            )

            label = fix_entity_type(
                entity,
                label
            )

            entities.append({

                "entity": entity,

                "entity_type": label,

                "confidence": confidence
            })

        # ==========================================
        # RULE-BASED IT ENTITYS
        # ==========================================

        it_entities = extract_it_entities(
            text
        )

        for ent in it_entities:

            normalized = normalize_entity(
                ent["entity"]
            )

            if normalized in seen:
                continue

            seen.add(normalized)

            entities.append(ent)

    except Exception as e:

        print("PROCESS TEXT ERROR")
        print(e)

    return entities


# =========================================================
# FIND ENTITY
# =========================================================

def find_entity(normalized_name):

    try:

        response = supabase.table(
            "knowledge_graph_entities"
        ).select("*").eq(
            "normalized_name",
            normalized_name
        ).execute()

        if response.data:
            return response.data[0]

        return None

    except Exception as e:

        print("FIND ENTITY ERROR")
        print(e)

        return None


# =========================================================
# CREATE ENTITY
# =========================================================

def create_entity(

    entity_name,
    normalized_name,
    entity_type,
    language,
    embedding,
    source
):

    try:

        response = supabase.table(
            "knowledge_graph_entities"
        ).upsert({

            "entity_name": entity_name,

            "normalized_name": normalized_name,

            "entity_type": entity_type,

            "language": language,

            "frequency": 1,

            "preserve_in_translation": True,

            "is_translatable": False,

            "embedding": embedding,

            "source": source

        }).execute()

        print(
            f"INSERTED ENTITY: {entity_name}"
        )

        return response.data[0]["id"]

    except Exception as e:

        print("CREATE ENTITY ERROR")
        print(entity_name)
        print(e)

        return None


# =========================================================
# UPDATE FREQUENCY
# =========================================================

def update_frequency(

    entity_id,
    frequency
):

    try:

        supabase.table(
            "knowledge_graph_entities"
        ).update({

            "frequency":
            frequency + 1

        }).eq(

            "id",
            entity_id

        ).execute()

    except Exception as e:

        print(
            "UPDATE FREQUENCY ERROR"
        )

        print(e)


# =========================================================
# INSERT MENTION
# =========================================================

def insert_mention(

    entity_id,
    source_sentence,
    detected_label,
    confidence,
    language
):

    try:

        supabase.table(
            "knowledge_graph_mentions"
        ).insert({

            "entity_id": entity_id,

            "source_sentence":
            source_sentence,

            "detected_label":
            detected_label,

            "confidence":
            confidence,

            "language":
            language

        }).execute()

    except Exception as e:

        print(
            "INSERT MENTION ERROR"
        )

        print(e)


# =========================================================
# INSERT ALIAS
# =========================================================

def insert_alias(

    entity_id,
    alias,
    language
):

    try:

        normalized_alias = normalize_entity(
            alias
        )

        existing = supabase.table(
            "knowledge_graph_aliases"
        ).select("id").eq(

            "normalized_alias",
            normalized_alias

        ).execute()

        if existing.data:
            return

        supabase.table(
            "knowledge_graph_aliases"
        ).insert({

            "entity_id": entity_id,

            "alias": alias,

            "normalized_alias":
            normalized_alias,

            "language": language

        }).execute()

    except Exception as e:

        print(
            "INSERT ALIAS ERROR"
        )

        print(e)


# =========================================================
# UPSERT ENTITY
# =========================================================

def upsert_entity(

    entity,
    entity_type,
    language,
    source_sentence,
    source
):

    normalized = normalize_entity(
        entity
    )

    # ==============================================
    # CACHE LOOKUP
    # ==============================================

    if normalized in entity_cache:

        existing = entity_cache[
            normalized
        ]

    else:

        existing = find_entity(
            normalized
        )

        if existing:

            entity_cache[
                normalized
            ] = existing

    # ==============================================
    # EXISTING ENTITY
    # ==============================================

    if existing:

        entity_id = existing["id"]

        update_frequency(

            entity_id,

            existing["frequency"]
        )

    # ==============================================
    # NEW ENTITY
    # ==============================================

    else:

        embedding = generate_embedding(
            entity
        )

        entity_id = create_entity(

            entity_name=entity,

            normalized_name=normalized,

            entity_type=entity_type,

            language=language,

            embedding=embedding,

            source=source
        )

        entity_cache[
            normalized
        ] = {

            "id": entity_id,

            "frequency": 1
        }

    # ==============================================
    # INSERT MENTION
    # ==============================================

    if entity_id:

        insert_mention(

            entity_id=entity_id,

            source_sentence=
            source_sentence,

            detected_label=
            entity_type,

            confidence=1.0,

            language=language
        )

    return entity_id


# =========================================================
# TEST PIPELINE
# =========================================================

test_text = """
I live in Ho Chi Minh City
and use PyTorch with
FastAPI and PostgreSQL
"""

print("\nTEST EXTRACTION:")
print(process_text(test_text))


# =========================================================
# LOAD DATA
# =========================================================

df = pd.read_csv(
    "data_600k_clean.csv"
)

print(
    "TOTAL ROWS:",
    len(df)
)

# =========================================================
# TEST SMALL FIRST
# =========================================================


# =========================================================
# MAIN PIPELINE
# =========================================================

for idx, row in tqdm(

    df.iterrows(),

    total=len(df)

):

    try:

        english_text = clean_text(
            row["english_text"]
        )

        vietnamese_text = clean_text(
            row["vietnamese_text"]
        )

        if not english_text:
            continue

        if len(english_text.split()) < 3:
            continue

        if english_text.lower() == "nan":
            continue

        entities = process_text(
            english_text
        )

        for ent in entities:

            # ======================================
            # UPSERT EN ENTITY
            # ======================================

            entity_id = upsert_entity(

                entity=ent["entity"],

                entity_type=
                ent["entity_type"],

                language="en",

                source_sentence=
                english_text,

                source="raw_data"
            )

            # ======================================
            # ADD VIETNAMESE ALIAS
            # ======================================

            if entity_id and vietnamese_text:

                insert_alias(

                    entity_id=entity_id,

                    alias=vietnamese_text,

                    language="vi"
                )

    except Exception as e:

        print("ROW ERROR")
        print(e)

print(
    "\nKNOWLEDGE GRAPH BUILD COMPLETE"
)